CREATE TABLE categorias
  (
    NUMCATEGORIA INTEGER PRIMARY KEY,
    NOMBRE       VARCHAR(50)
  );
CREATE TABLE productos
  (
    ARTICULO     VARCHAR(20) PRIMARY KEY,
    DESCRIPCION  VARCHAR(70),
    NUMCATEGORIA INTEGER,
    PRECIO FLOAT,
    CONSTRAINT FKPRODUCTOSCATEGORIAS FOREIGN KEY (NUMCATEGORIA) REFERENCES CATEGORIAS (NUMCATEGORIA)
  );
CREATE TABLE ESTADOS
  (
    ESTADO      VARCHAR(2) PRIMARY KEY,
    NOMBRE      VARCHAR(40),
    ABREVIATURA VARCHAR(6),
    PAIS        VARCHAR(5)
  );
CREATE TABLE MUNICIPIOS
  (
    MUNICIPIO INTEGER PRIMARY KEY,
    NOMBRE    VARCHAR(90),
    ESTADO    VARCHAR(2),
    CONSTRAINT FKESTADOSMUNICIPIOS FOREIGN KEY (ESTADO) REFERENCES ESTADOS (ESTADO)
  );
CREATE TABLE TIPOSASENTAMIENTOS
  (
    TIPO               INTEGER PRIMARY KEY,
    NOMBREASENTAMIENTO VARCHAR(50)
  );
CREATE TABLE COLONIASASENTAMIENTOS
  (
    NUMERO           INTEGER PRIMARY KEY,
    NOMBRE           VARCHAR(90),
    TIPOASENTAMIENTO INTEGER,
    CPOSTAL          VARCHAR(5),
    MUNICIPIO        INTEGER,
    CONSTRAINT FKCOLONIASMUNICIPIO FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIOS (MUNICIPIO),
    CONSTRAINT FKCOLONIASTIPOASENTAMIENTO FOREIGN KEY (TIPOASENTAMIENTO) REFERENCES TIPOSASENTAMIENTOS (TIPO)
  );
CREATE TABLE TIPOSCLIENTES
  (
    TIPO        CHAR(1) PRIMARY KEY,
    DESCRIPCION VARCHAR(60)
  );
CREATE TABLE CLIENTES
  (
    RFC               VARCHAR(14) PRIMARY KEY,
    NOMBRERAZONSOCIAL VARCHAR(160),
    TIPO              CHAR(1),
    SEXO              CHAR(1),
    FECHANACIMIENTO   DATE,
    DIRECCION         VARCHAR(160),
    ACTIVIDAD         VARCHAR(160),
    COLONIA           INTEGER,
    EMAIL             VARCHAR(160),
    TELEFONO          VARCHAR(14),
    NUMERO            INTEGER UNIQUE,
    FREGISTRO         DATE,
    CONSTRAINT FKCOLONIASCLIENTES FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO),
    CONSTRAINT FKTIPOCLIENTES FOREIGN KEY (TIPO) REFERENCES TIPOSCLIENTES (TIPO)
  ) ;
CREATE TABLE TIENDAS
  (
    NOTIENDA    INTEGER PRIMARY KEY,
    NOMBRE      VARCHAR(90),
    FECHAINICIO DATE,
    COLONIA     INTEGER,
    CONSTRAINT FKTIENDASCOLONIAASENTAMIENTOS FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO)
  );
CREATE TABLE EMPLEADOS
  (
    NOEMPLEADO      INTEGER PRIMARY KEY,
    PATERNO         VARCHAR(30),
    MATERNO         VARCHAR(30),
    NOMBRE          VARCHAR(30),
    SEXO            CHAR(1),
    FECHANACIMIENTO DATE,
    FECHAINGRESO    DATE,
    TIENDA          INTEGER,
    COLONIA         INTEGER,
    FREGISTRO       DATE,
    CONSTRAINT FKTIENDAS FOREIGN KEY (TIENDA) REFERENCES TIENDAS (NOTIENDA),
    CONSTRAINT FKCOLONIAASENTAM FOREIGN KEY (COLONIA) REFERENCES COLONIASASENTAMIENTOS (NUMERO)
  );
CREATE TABLE VENTAS
  (
    NOVENTA  INTEGER PRIMARY KEY,
    FECHA    DATE,
    CLIENTE  INTEGER,
    EMPLEADO INTEGER,
    TIENDA   INTEGER,
    TOTAL FLOAT,
    CONSTRAINT FK_VENTASCLIENTES FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (NUMERO),
    CONSTRAINT FK_EMPLEADOSVENTAS FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS (NOEMPLEADO),
    CONSTRAINT FK_VENTASTIENDAS FOREIGN KEY (TIENDA) REFERENCES TIENDAS (NOTIENDA)
  );
CREATE TABLE DETALLEVENTAS
  (
    NOVENTA INTEGER,
    CLAVE   VARCHAR(20),
    CANTIDAD FLOAT,
    PRECIO FLOAT,
    IMPORTE FLOAT,
    CONSTRAINT FK_NOVENTA FOREIGN KEY (NOVENTA) REFERENCES VENTAS (NOVENTA),
    CONSTRAINT FK_CLAVEPRODUCTO FOREIGN KEY (CLAVE) REFERENCES PRODUCTOS (ARTICULO)
  );
CREATE TABLE FACTURAS
  (
    NOFACTURA  INTEGER PRIMARY KEY,
    FECHA      DATE,
    NOVENTA    INTEGER,
    RFCCLIENTE VARCHAR(14),
    CONSTRAINT FKFACTURASVENTAS FOREIGN KEY (NOVENTA) REFERENCES VENTAS (NOVENTA),
    CONSTRAINT FKFACTURASCLIENTES FOREIGN KEY (RFCCLIENTE) REFERENCES CLIENTES (RFC)
  );
